### ISSUE TITLE
Careers: Find more suitable word for "dangerous"

### ISSUE THREAD

**Issue by Perleone** [taustation-fan/taustation-fan.github.io#13]
Career tasks that can land you in _jail_ are designated as **"illegal"**, which is the perfect fit.

Tasks that are detrimental to your _health_ are currently termed **"dangerous"**, but that is not unique enough, since the danger can be both to your health and to your freedom.

Therefore I propose we switch to another term that is more closely related to health, like **"harmful"** or **"unhealthy"**. Additional proposals are welcome.

**Comment by Perleone** [comment]
I just noticed that the game itself uses these two words:
> if the task is illegal or dangerous

But that should not prevent us from making a better guide. ;-)

**Comment by particle** [comment]
Definition of dangerous 
1 : involving possible injury, pain, harm, or loss : characterized by danger

you see "dangerous" as also meaning "possible loss (of freedom)".  i can get behind that.  "harmful" could be a good fit. the only other term i can think of, which is perhaps more esoteric outside of legal settings, is "injurious".

"unhealthy" sounds to me more like it's related to the state of stats, rather like "toxic" (which would be specific to stims, i suppose).  i don't think i've ever performed a career task which has ended me up in sick bay, so i can't tell if failure on a "dangerous" (currently) task depleted stats above the normal amount.

my ranked vote for terms proposed so far is: 1) harmful, 2) injurious, 3) unhealthy.
